{
  "article": {
    "para": [
      "[Install_pluguin]",
      "*//java.script.CSS.ChiutScriptData-Sync.SSL/",
      "*//java.script.JoitRuntools.license.als;/",
      "*//java.script.token_CSI.SHAUKELLER.SpotcheatCheck.Netlink-Direct.CSS/",
      "*//java.source.code.database-PlayedviwerPareate.Job.USB.NLP.js/",
      "*//java.script.INCEP.WarylendGoogle.CAchturPlugCast.BestelClouad.js/",
      "handleth=\"revindecate\"source=\"connect\" extension=\"setoutimput program Files\" NISSDISCK=\"C:/@cddata=cmd:command dir -d /r cd In Corrent\"(true); Atribute_title=\"menu-Loguin(java.script.JoitRuntools.als)domain\";space=\"lackplaxrename\";menu=\"bouard-Archive\";document=\"programData\";plex=\"text-menu1\"",
      "Usdir =\"cd-data=ac-dc ceplaeject_ejetct=\"java.script.root.archell.lu\"uroot=\"flashinstall\"(cmd.exe=\"true\")code=\"title-plug-spacebar\" res=\"flash=\"now dreath-this in -devtool\",\")\"true\" (class=\"winlaut\" metodo=\"menulockup-drewarwollserve\";relatory=\"guidemenu-text\";text=\"splageremoto\";add=\"button=\"r-pixel_606\"leigth-Space=\"Parentraditory\";\")true\"(unlauch=\"controlmenu\")], &#13;",
      "comand(souplat=\"index.ind\",repageNotify=\"Banwit\" vps=\"config-log;",
      "DataTransferItem ='ppeline_create\"Lic_lacerget-one=\"unistall\" demp=\"comand:reply &lt;heidtlevelmenu&gt;&lt;control&gt; teme=\"renamer\" nowrester=\"pagelink\"&lt;vulchermenu.alu&gt;mistacker=\"browser_dump-menutitle\"&lt;Egixastar-updown&gt;&lt;rap=\"Unlaust&gt; bouard=\"feedownmenu-modo\";",
      "molutenuther=\"space=&lt;layout&gt;reblaout=\"configuration\"\"traceopencenter=menucomand=\"cmd\"(true)\"lowspage=\"no&lt;spacemenu-title&gt;\" dir/cdms=spectdrincatfat rrd=cdr;loading....",
      "full_extraction = \"mesting\" refourseparear=\"implemed -a font-redrect=\"responder\" fragment=\"folder\" sulrefect=\"action();dempass=\"mestract-adjust\";\"true\"(log=\"status,perimargelife.bef\",\"ref=\"sys\"",
      "log_page=\"chuckoout-com-menu1\" g-reset=\"frear\",&lt;plastimput=\"comand&gt;corrent=&lt;type-program&gt;reboot=\"plagetroywed-Uboot\";",
      "PerformanceResource=\"thunning\"",
      "Program:cmd:Rowelle_receiver(true);",
      "[Scalltaring_my-voice]",
      "Info:RenexVoiceBuild.vsi;",
      "fastlogout:\\Launch\\windows\\system32\\Appdata\\temp\\progemfiles(x86)\\Microsoft\\samp\\flet_sheatsemp\\survival\\Security\\han\\rentable\\corereply\\pendaple\\art\\suport\\Triveal\\Action\\in-Span\\);",
      "PlaceRetorn=\"Resision\"{region,Linguagen=\"Portugues ==PTbr\"popult=\"Linguagen,DominationStuto.Control-ReportResource.rec,Palhar=Encoding,Fowat.craleweve.source,",
      "PlenamentImagen=\"Senrap\"Sound=(\"trevase_Linguagen\") Lesodown_play=(\"device\") EmplantVoice=(\"Sac_argelie\") Bindick=(\"Bland_audio.mp3\") Next='Visible_relation\"},Advertion=(\"PlugMout.Ack\")action=\"{Afilliate}\"_Verssion: _v-1.00.02')",
      "Manifeste=\"VoiceImterplete\" Element=(\"repearch\") Extration=\"Document\"{Event=\"Audio\"/nor-out=\"Sourtide\"} Private=(\"Icopatible\") Essensiais=(\"Atributo\")",
      "Ebay_Space:'Volweritsh_/dir/Suport:Pluguin C-Drive\"",
      "WizarlayerShell:\\WinVilbersShell\"(Enside=TableWizar) Implement=(\"Winsheset\")_Implamap=(\"Niwble_ChargeMap\")_Sync=(\"Eysebin.data\")_Plenseaple=(\"PallyPlay\")_Suport=\"Systemap\"Linguagen-Ipress=(\"SquagueSempMap.awp\")\"(flaker=\"Part-pt_BR\")\"( Local=\"Brazillian\")\"(Liguish=\"Portuguese\")\"(WefDos=\"IC_ISO/IN-DOS\")\"(Seo=\"Trenclearchive\") (Plasmap=\"Trideimagen\")_Verssion=(\"voice.avc\")_Voice=(previwer\")Planeament=\"Impride_LiveDevice?\" voice=\"Assistent?(java.script)APIaudio.Java.script!offline-intro-#2/Seo=\"wifi\"-VV+='onlline'",
      "Conjunto:AC_DC-Plataform/Param=\"Pausebreack\" fusion=('windowsOSE-Replace_Emplement',)",
      "Command:\\Windows_Explore'Audition=(\"folha\")Hell:OrtgameVoice\"(true);",
      "F:\\Path\\Fast\\System32\\Users\\AppData\\local\\temp\\Campeker.pad",
      "Generator=\"Resolution\"Suplemant=\"Resoucers\"Piexl-1x60/Pixel-%50%-+40P/Lusion=\"BadClan0\"Buffer=\"Res\"/Inelaset=\"[Pleygrauld]\"/STA=\"Gepad\"Null=\"Flash\"/Kebauld=\"CamSetCless\"/Set_Inside/Feed_=SpeceBar/dyngo-oll_Bland='[0x0100f00c00]\"/Flext=\"[\"X10\"]=[\"X30\"]\"/Prevewer=\"Casecache'",
      "Lisence by:\\_ClaupseKewe=\"Radio\"/Freend=\"Houther\" Caution=\"CampelwerDrive\" SportCenter=\"CleanRay\"Valid=\"Setup\" Recourd=\"Source_FileVoice\" PandaCast=\"SampleKacker\" prevewer_acusticSetup-Print=\"Resource\"",
      "Linguagen:\\Enterplete=Emulation(class=Clouadsync setup-Enterres=\"ServiceVoice\"Scaltlang_me-voice=\"username\"(true);Deby=\"Control\" Primary_type=(\"Amc.pav\")(?)Emotionfusion=\"EmporyEmergence\"{'Calc.gawerwilleSnesplock.dsd\"}",
      "Padtwin=\"enciclopede\"fx=(\"c8t4b110c20r4-bu\")Voice_End_Waller=\"Ipeg\"/Allias=\"RestoPreve\"Cousm=\"font\"kiobarg=\"Proff-ANA\"{Casck=\"proff-ANA\"};",
      "IDVoice:/Enjoy-device=\"Ejustfreendvoice.Assistent,#%\"jaccer\"% %Source%,Snour=\"Suplentname-OS81@wep-Alliascepkey.script\"",
      "MyRoboart=\"OtagamaVoice\"Java.script.voicerenc.js\" All/Acervo/Assistente={\"Coallpecker\"}_JenioursPlit.java.script=\"Jet:Logo.site-_Google.com.br\" Enviar=\"envock=?#perguntas&amp;respostasdiretas{Printamide=\"midia-cursor\"/device_java.ksl},{Ico_sentable.txt.has,}clivelle_messeger:{Username=\"Essetask_Wello_pov/soundnet.sev=\"Clan=\"openSource\"},{Renwise=\"voice\",Scassent=\"recourd\"/voice_rec.ari},AllAudio={airplay.swf},{ActionPrive=\"delay\",}{Aplause=\"kenfarti\"}{,Reseved=\"Mase_withe\"/sync=\"(voiceEnd-drive=prive.avs)\"",
      "Trasference=\"Resource_Audio/var=\"intro\"/Sploint=\"Messager\",Mister_Sampeckers=\"{Audio.mp3/AudioPlayer},Var=\"Aaro\",Paste=\"AudioControl\"/EnviosLess=\"Asunt-Audio.mp3\"}&#13;",
      "Command:\\Set-PageURL_Messager/Param=\"voice\"value=\"audio\"/Audio.Mp3.ogg/Var,Custon_Servidor:CursorNepk.sdk,{,Implement=\"Messager\",} Format=\"Resoucers\"UnityPlayer={,Filepast=\"Username\",} {,Voice, Skeep_get,\"}/PlayerAudio=\"auto\"Please=\"title\",Stop/Imput/{,EBoot=\"fastboot\",} {Realflash=\"boot\",} {,Source=\"Messager\",} {,Voice\",Assistent.av],[{,Stingue=\"Linguish\",AutoPlay\"},\"?.../!!!\"}",
      "Vayers=\"Planit_Exemple\"",
      {
        "#text": "Suplemant=\"Resouces\"",
        "para": {
          "para": [
            "Playervoice=\"rename_Enengistall\"audio=\"emitirsom post secundary==kack-username=voice.ivs,",
            "Playervoice=\"rename_Emengistall\"Elencorecdisend.cursor_cup.dsv==kack-username=voice.ivs,",
            "SpyCenter=\"List-username\"",
            "Converssion=\"voice\"",
            "Empite=\"SteanClip_Voice\"",
            "Capture=\"ScapSuotPack\"",
            "captche=\"ScapSuotPack\"",
            "multipleface=\"Infoburguer\"",
            "Emplement=\"java.script\"",
            "Emergence=\"AC-Agent\"",
            "Allflayer=\"folha\"",
            "Wevicon=\"UsersProgram\"",
            "Hellpock=\"Allias\"",
            "Modo=\"PortalnegenfiutiUltra\" hery=\"scripted.pvx\");",
            "Plack=\"Neograund\"XP=\"Friores\"",
            "adjust=command shit in vrs:cd:Android\\system\\Appdata\\local\\tmp\\filesApp\\Exb\\update\\enfitrack\\pack\\propieded\\HigLaut_run\\Redme\\filepast\\past\\",
            "fouded slot=on mod=choitpad cid=rename_sourcePack(LocalGet_Imput=Report_system(true);",
            "get if Not token/Interno=filedata buscSearch=\"Stick_menagerComon\"replese=folder Open=Externo_PCL:\\Ucher Criate Log=Louading...(0=100%=1000,00_UnfSpingFeldetch_Loock\"New=stramingFiles_Source not=status;",
            "backup = press-pack -by source=\"Arquivos\" value=\"post\" prodoct outimput=\"Extractor\" cheats=\"newpast\" folder-type=\"past\"/ config token = on copy/y After=\"filepastname = newpast\" (dev1 =\"filename-past\" copy/All&amp;=\"full_heyrit\" get/gerate==&gt;\"VRS-002\" ast.dev=\"info\"(dir=\"Scopy-1\"&gt; y = REDCH===&gt;&lt;REDCH=\"100%\"&gt;&lt;/REDCH&gt;",
            "start = create past=\"Arquivos\" source=&gt;REDCH low dir object louad=\"loading:4.3.2.1......./onshet_l001.h=0 time=[24:00:00:00]",
            "bootlouad=\"Wisekeep\"Sync-\"hackUnilimited\"flashinstall=\"Aeropicture\"(wild-line)\\willeDay=\"Standy_memory\" warnnig=\"controlador\"Wariwed=\"program_The.elf=\"traindiwil_hackers\" local C:\\patch()\\localcontrol=dommain/wildline/portal/creete/done readonly.cvc/all/system/LocalUser/Userdata/usdir/dir/louader/rentarie/storang/update = cd/jarmmt autocontrol = samey-lusionwork.dll dir/temp/log/command=\"cwm=\"ultilite#parear\"sloff=\"sofitline,install\"",
            "Exession:EuginuserKeep/Cass:(Exemplo) Browser\\Source\\Ultimate_PautURL\\part_test\\Suite\\wirst-Whatssap.tsc\\outPack=(\"Profile-EmailSeans\")",
            "HotspotSetpoit= \"C:\\fastboot\\boot\\Leewirender\\Gatwork\\Rawise\\Elevitall\\Gsm\\Sat_extrato\\",
            "capriger=\"SuletionspanCriete\"logMod=\"pupger\" Next=\"aplication\") Corrumped=\"calctime\");",
            "Eboot=\"rename\"title=\"realtunnel\"(foto)bamcheck=\"nowdir\"propy=\"prograns\"(.lc)/petgress=\"aplicativo\");",
            "BirEvent=\"Ckack\"Pameshuck=\"Wirrist\"Deffonwit=\"gosckakedit_Centuise\"Brimout=\"Craglle\"Vetry=\"Esses(sys-extension)\"Papiget=\"frenet\"Acent=\"wabtssappl_Whatssap.but\");",
            "jvs=patch:\\system\\local\\Appdata\\temp\\Users\\program\\localFlies\\programs\\temporary\\source\\margen\\widget\\tealouad\\Mass:\\\\target=delet",
            "get=%set% patch:\\system\\local\\Appdata\\temp\\Users\\program\\localFlies\\programs\\temporary\\source\\margen\\widget\\ProgramFiles\\users\\memorystick\\Disck D:Wild\\token\\doc\\propieded\\local\\diretory\\Upload\\menssager\\Install\\Pack\\Unlocked\\UDP_USBserie\\Logout\\Memory\\UPL_FilesApp\\Apps\\",
            "src=bat.=creator imput=\"document\" ddr=shell localsetting=\"backup\" reset=\"propoursmacktoken\" alu.dy=\"menssager\"",
            "mrdir:\\\\cmd.bincd tree open=\"program \"C:\\system\\appdata\\app\\temp\\Propieded\\corrent\\rmdir:pront\\document\\spoller\\mrdir\\cd=windir%dir%\\diretory\\add=\"one1=\"springmacker\\allow=\"setdir\"pront=\"position_event\\senable C:\\\\option\\Sloung=\"offset\\typetouch_Rengelaout=\"add-[on]=[on/?=yes)]/all_luns/add=\"out\"[off]=[off/?=no)]\"[open]=[playout],stricker=\"unloknow\" pass=[enter],pressione=\"onblock\"],tabelstaker=\"unlook\"",
            "getsub=\"shourtcut %cd% = windowssysfile.exe/Imcd.cmd/based/bad/clin/action/widlen/setup/setcontrol/local/windir/dir/temp/programfiles(x86)/file.exe,",
            "octpickers:\\line0\\programfile\\auto\\line1\\system=mass:\\\\patch\\controllocal\\winset\\local\\temp\\%Username%\\program\\Pront comand(.exe)\\filebat.bat(startup)executaviel=\"Cmd=nullCD\"All%cd%Program/?setup",
            "sealineinstall reset-open/goto = baylouad/filredfit/(blecaut=\"teskout_imput);",
            "lcdm = param=\"parisetime\"/patch/install/all_Parier/ult-drivemass://settinglocalrenderlote.gks/envesurdesh.dll(unlook);delete&amp;lote=\"LocalUsers\" control\\setting\\setup\\wn?/keep/ping=\"InstallJutscriptgg.gco\"/Entry=\"Install\"Winrdd=\"null/Copy=\"rename\"lote/NowPast/pfw:program files (x86)CD%SvcSave0=\"download\"",
            "save0=copy0/6 lacprint/session =\"hachbouardcam.cut\"/populti=\"Addon\"(list=\"Extracion\" Inesistent=\"restory\");(optionfile=\"protetion\"(all);recente=\"Status\")",
            "save0=copy3/1 lacprint/session =\"hachbouardcam.cut\"/populti=\"Addon\"(list=\"Extracion\" Inesistent=\"restory\");(delet=\"packager\"/all();restart=\"save\")colect=\"Setpoint_extrato\"",
            "dsr = boot/stauker=\"logouff _off/Buguer=\"Scan\" widget=\"ContentName\"(block)/Primary=\"registro\"/Pront = DMC-Unlocker/Restart=\"table.vgr\"",
            "wiserkenfly = patch\\frashinstall\\boot\\system\\local\\Appdata\\temp\\Users\\program\\localFlies\\programs\\temporary\\source\\Backup= \"C:\\\\system\\Appdata\\Apps\\temp\\packager\\Hotlist\"",
            "vgg=\"echo sence\"primary=\"loop\"notffing=\"pautclid\"resigner=\"uffow\"less=\"keep\" partition=\"localpast\"ultillity=\"users\" relation=\"exirwheditco.cvb\"",
            "boot=contentlogwin%temp%Corrent/cd~%config%res%watchecker/LapStyleScreen=\"imput-parear\"",
            "Windows=\"localsetting\" control=\"root_retarden\" setpoint=\"set\"campriger=\"Selletion_Span-Cliche\"logMod=\"pupgr\"(Next_aplication)/Corumped=\"calctime\"",
            "boot=\"carrier\" fastboot=\"rename\" rename=\"folder\" detais=\"realtimeline\"(plug_rellet=\"sersgefkot.kot\" bamcheck=\"nowdir\"propy=\"prograns(.lc)/paintgress=\"aplicativo\"",
            "hostlist=\"WereSheatSmonping.ilg",
            "imsdd=\"dpdatausrdir\"",
            "lote=\"format\"",
            "icms=\"dpdatausrdir\"",
            "csdr=\"friends\"",
            "cuck=\"perield\"",
            "sudoku=\"kemarilesity\"",
            "bickpaint=\"scripted\"",
            "font=\"gustwitte\"",
            "lote=\"formation\"",
            "CSR=type/file/temp/exobin.irl",
            "get=patch/system/windir/dir/tmp/deep/profile/assept/checker/temporary/margen/w/tealouad/Mass:/target=delet",
            "get=%set% ProgramFiles\\users\\setup\\memorystick\\Disck D:Wild\\token\\doc\\propieded\\programfiles\\local\\temp\\diretory\\Upload\\menssager\\Install\\Pack\\Unlocked\\UDP_USBserie\\USB0.nfn\\Log\\Memory\\UPL_louader\\FilesApp\\Apps",
            "csr=filebat.&amp;%creet%==Upload()direct:document ddr=Sheart-imput(shell)\\local\\setting=\"backup\"program=update root=setup renwiuerset=\"propoursmacktoken\" alu.drs=\"controlmenssager\")",
            "select=fileApps\\all\\Users\\prograns\\localsetting\\Usdir\\dir\\filesApps\\Apps\\prograns\\packager\\token\\select\\option=1",
            "command:\\\\?\\localdata\\CTPC-SDMID\\ADM\\temp\\Adiministrador(Username)Pront=\"Cddata\"\\Help\\Propieded\\tugClient\\Add_shourtCut\\Ax-shourtcut\\system32\\local\\Appdata\\temp\\#mmcrdir==/?null",
            "rmdir:\\\\cmd.bincd tree open=\"program \"C:\\system\\appdata\\app\\temp\\Propieded\\corrent\\rmdir:pront\\document\\spoller\\mrdir\\cd=windir%dir%\\diretory\\add=\"one1=\"springmacker\\allow=\"setdir\"pront=\"position_event\\senable C:\\\\option\\Sloung=\"offset\\typetouch_Rengelaout=\"add-[on]=[on/?=yes]/all_luns/add=\"out\"[off]=[off/?=no)]\"[open]=[playout],stricker=\"unloknow\" pass=[enter],pressione=\"onblock\"],tabelstaker=\"unlook\"",
            "select = patch\\system\\Ulaunch\\windir\\usdir\\dir\\temp\\res\\Appdata\\App\\prograns\\packager\\token\\select\\option=1",
            "[keyBoard]",
            "REGISTRE=BOUARD-MENAGER",
            "@echo off",
            "PAINT=Cmd.exe",
            "HUDD-ID: Echo=\"C:\\System_Machine\\Mastered\\PCI_Ime-ID\\ID\\Desktop\\%System%\\WinSet\\Setup\\Usrdir\\Dir\\Loguin\\Key\\sysMachine\\CoNtrol\\correntcontrolset\\setcontrol\\Param\\Username\\Users\\Propieded\\User_Bur\\Bowshese\\Profile\\Administrador\\Domain\\$Admin\\Senable\\key",
            "REVIWER=\"WINSET/TEMP/CET/UDFTS_US/DSTN2=TECHAR/TKDF=KEYREGIZE SYS=LIVEDRIVE/#EXTRITY=VIDE%EXTRAT=.EXE/RGFMI.INI=CONTEX/VAST_NAME:ROOT/CE:RESTART/NUMBER:NUCLEO/PCRD:TCRPI-IN/PAR=0-000103746_UNITY/CTRL:SAP/CPMC=PCI/EXIT=AGENT/SKYN_BOUARD=REVDATABOARD/FAT,32/WINDOWS/SYSTEM32/APPDATA/SYSLOG/$WINSET/SETDATA/%WINDIR%/DIR/EJECT/CONFIG/VIWER=ATAIL/PC-MRSGD=PCI-ECOM_CAMPIRE/COMPUTER/BOARD=DIRNOWBOARD",
            "REVIWER=\"CUBIGET/SEMPSHOUYD/KEY-BOUARD/SETDIR=REGISTRE/GRAFT/GREEN/GEN/VEID/GEV=CUB_SET/TEYBO-SIRCE=WIN~IVEN%DRIVE\\D:\\DRIVE\\KEYBOUARD\\SENTCROUSE\\TECHAR\\FRIDGEKEY\\BROSKEY\\CODE=ROOT\\SETUP\\EXTRAT=HARDWERE",
            "reviwer=winset/cet/udfts_US/DSTN2=techar/TKDF=keyregize sys=Livedrive/#EXTRIT=VIDE%EXTRAT=.EXE/RGFMI.INI=CONTEX\\VAST_NAME:ROOT/ CE:RESTART/ NUMBER:NUCLEO/PCRD:TCRPI-IN/PAR=0-000103746_UNITY/CTRL:SAP/CPMC=PCI/EXIT=AGENT/SKYN_BOUARD=REVDATABOARD/FAT=32/%WINDOWS% =WINSET%SETDIR/DIR/EJECT/CONFIG/VIWER=ATAIL/PC-MRSGD_PCI-ECOM_CAMPIRE=COMPUTER/BOARD=DIRNOWBOARD",
            "OPEN=pad_bouard_keybit-in data=\"par\"bouard=\"loading\"spool=\"push\"control=\"closestop\" diretory=\"C:\\\"}",
            "LOADING=SECOND_REVIWER",
            "Primary=Spool_Key",
            "Skyne=Password",
            "Magekey=Password",
            "HUDD-ID=Key&#13;",
            "reserve_ID=key",
            "Rowss=thedy-bouard",
            "Flaiedit=ssdcode",
            "GRD=PCI-COMPUTED",
            "REDWARE=SKESH_TOMBOUARD",
            "READ=TECHARPAD",
            "open=Louader",
            "LOADING=SCANDRIVE",
            "Gagenpad=Advance_Arcade",
            "Gama=RapEdit_Control",
            "Geting=FlashGrid",
            "Hitach=WeserbuildDump",
            "Hex=TogenDump",
            "Refrash=WiseDrive",
            "Par=Wick-wifi",
            "Sellent=CotrolSetup",
            "Prev=Action",
            "Gawever=GoedPeg",
            "Nugueid=Virescop",
            "Emak=RouchDown",
            "Setpall=Startget",
            "Exo=8",
            {
              "#text": "Salt=4para>",
              "para": [
                "ELOCK=d0c",
                "dstd=TouchPad",
                "Sgbios=FlashCut",
                "BIOS=Tlemtibi-Higpad_Usb=Fragmatic/ Dcr=Control/SutBios/Board_Gavedrive/Usb/Externo/Bloc_DC=[0x005100104]",
                "Frameset=%Fixer%~ADvance%Urv~Device(Raperware)\\GameCotrol\\Cover_Artige\\Setpall\\Gamepad\\Controls\\KeyBouard",
                "Par=flindwer(esp)%~Shell%FatBoost%Grid%UPack(true);",
                "MegeiPeg=(true)",
                "Hav=Resky",
                "Blould=trevCovControl(false);",
                "Bloc=Pratice",
                "id_Flash=EaseDrive\\Device\\Winsepting\\Local\\Storang\\Devide\\Driver\\KeyBoard\\Key\\CekPack\\Ifreen\\Down\\Advance\\KeyPad\\",
                "Dlc=5",
                "Befour=touch",
                "Befpur=Act",
                "trdc=ID",
                "trdc=Addr&#13;",
                "gprs=Find",
                "Atd=1",
                "Atx=1",
                "Epx=13",
                "Epx=0",
                "Error=Set-A",
                "guep=Downt",
                "tcr=[14.877.24]/Best",
                "GPeID=[4528182]/Best",
                "Breet=Busther(Act)din~(true);Blould~Esc=Jet(true);",
                "Benemoud]",
                "[binary=[j],[p]/W fuext=\"eichodrin\"fuexdd=\"origamet\"keybre=\"alp-aero=\"4\"keybrid=\"alp-aero=\"4\" index=voltrack ducs=\"volume\"Ntd=[0],padge=\"downcontrol0\"hubcrom=\"select\"keepcage=\"multistik-700\"number=\"breack_/L10-v6\"",
                "BloseBand=Botton-controller",
                "[Control]",
                "baseconsola-p=Up/f2,l1+r1 = f1,l2+r2",
                "Baseconsola-1=Down",
                "Baseconsola-2=Eidth",
                "baseconsola-3=reidth",
                "[Botton]",
                "Bottonbut-p=Up-ehect",
                "Bottonbut1=Down-eject",
                "Bottonbut2=Eidgth-eject",
                "Bottonbut3=reidth-eject",
                "[Select]",
                "Start/Select",
                "[Pause]",
                "Stop=Start",
                "[TouchPad]",
                "SentDumop=Vallid",
                "tarchdown=Dead",
                "Vrev=Chouther",
                "Pgmd=Control",
                "[Control]",
                "Allcontrol=consolaControlator",
                "Farve=urv dev=3 umc=1 bit=1100 cov_padrelaauser=0-9/exo /-t jump nor=\"button\"01src=\"stadby\"",
                "Ver=\"vouk\"",
                "Even=\"now_repertory\"",
                "Cepid=Atd",
                "auto=start auto=damarge-select",
                "auto=select&#13;",
                "auto=start auto=damarge reset=\"SysLanwerchetCache\"",
                "clouse-span=\"auto-reset\"",
                "setup = option=sloff",
                "boot=logouff/loading/shourtgot/.bat=\"clickScouper/syscop/Speedfulver/Anyloop-span_reasigne/unloock/setting()open=auto delet=\"status/WL/WL_password-iserid\"",
                "1cmf=span fat Add%control%/Linkdir=\"set\" auto=Update auto=reboot auto=damarge/select",
                "1cmf=Start fat Add%control%/Linkdir=\"set\" auto=Update auto=reboot/start=select",
                "loading=SysLanwerchetCache",
                "antolog=SysLanwerchetCache",
                "loading=checkpoint",
                "loading=SysLanwerchetCache",
                "stop=session trev-online/off in rdd=1-f0 read-on=file-Status settinglist=\"option\"(true);Livre",
                "imput=setting",
                "launch=certifing-launch.ehs",
                "protocol=config-launch.ehs",
                "unt=setup",
                "config=vatstartup",
                "open=vtrlook",
                "csd=option",
                "copy=furgn.db",
                "lts=furgn.db",
                "loading=setting",
                "auto=reboot",
                "rmft=cmd.exe louader=\"registro\" local=\"flash\" acf=\"config-launch.ehs",
                "start=cmd.exe louader=\"registro\" local=\"flash\" acf=\"config-launch.ehs",
                "lts=reboot",
                "start=\"lts=reboot;"
              ]
            }
          ]
        }
      }
    ]
  }
}